### PR TITLE
Removed more info history filter

### PR DESCRIPTION
**Pull request by fOmey**
Fix for #6

### CODE REVIEW

**Review by Madelena — CHANGES_REQUESTED** [review]
How come?

**Comment by Madelena** [comment]
Yeah, filters interfering with overflow is a problem in #6.

I'm looking for help solving it without sacrificing this feature. It's nice to have the chart in the color of the theme that is not just blue.

**Comment by fOmey** [comment]
> Yeah, filters interfering with overflow is a problem in #6.
> 
> I'm looking for help solving it without sacrificing this feature. It's nice to have the chart in the color of the theme that is not just blue.

I see, what if we apply the filter directly to the `canvas`, `chartTooltip > title` & `chartTooltip > div` containing the tooltip text?

I wasnt able to figure out the css selector required to do so.. however I did test it and experienced no overflow issue.

**Comment by Madelena** [comment]
Yeah I couldn't figure out the css selector either. I asked the folks on the card-mod git but I haven't gotten a solution yet: https://github.com/thomasloven/lovelace-card-mod/issues/200

**Comment by fOmey** [comment]
> Yeah I couldn't figure out the css selector either. I asked the folks on the card-mod git but I haven't gotten a solution yet: [thomasloven/lovelace-card-mod#200](https://github.com/thomasloven/lovelace-card-mod/issues/200)

I managed to get a working selector for the canvas, its messy but it kinda works?

It's behaving strange tho, the css properties only apply if I refresh themes while the more info dialog is up.. but my theory does indeed work:

Capture

**Comment by Madelena** [comment]
That's not messy at all! It's brilliant. 😀 

I can't replicate it on my side but feel free to make a PR.

**Comment by fOmey** [comment]
> That's not messy at all! It's brilliant. 😀
> 
> I can't replicate it on my side but feel free to make a PR.

I've modified my previous message, give the code another try.

I'm reloading themes in home assistant from the development page in a different tab while the more info dialog is open in another.

lovelace-card-mod seems to be watching for theme reloads actions which is why I think its triggering the css to be applied.. its strange that its being lost when opening the dialog normally tho.

This is not a working solution so I won't create a push request at this stage..

**Comment by thomasloven** [comment]
I learned about this on April 1st. Apparently the `filter` property resets the z-stack for some reason, such that popups, context menues, select boxes etc. all render behind the transformed element and become unusable if you e.g. add a small rotation to every card...

Regarding the reload problem I will need to look into that specifically. There's lots of timing issues all over with card-mod.

**Pull request closed without merging**
